server.port: 8602

server.session:
  state.jwt.secret: "YTkBY+iXQxPt6e3UG4/VRHAHXePJZTSyc3cAE6btwfI="

solon.app:
  group: folkmq
  name: folkmq-server

solon.logging.appender:
  console:
    level: INFO
  file:
    level: INFO
    name: "logs/${solon.app.name}"
    rolling: "logs/${solon.app.name}_%d{yyyy-MM-dd}/%i.log"
    maxFileSize: "10 MB"
    maxHistory: "7"

solon.logging.logger:
  "root": #默认记录器配置
    level: INFO
  "io.netty":
    level: WARN


folkmq.admin: admin
folkmq.snapshot:
  enable: true
  save900: 1
  save300: 10
  save100: 10000


#folkmq.broker: "sd:tcp://127.0.0.1:18602?@=folkmq-server"

#folkmq.access:
#  user1 : "YapLHTx19RlsEE16"
#  user2 : "YapLHTx19RlsEE16"