server.port: 13602

solon.app:
  group: folkmq
  name: folkmq-server

solon.logging.appender:
  console:
    level: DEBUG
  file:
    level: INFO
    name: "logs/${solon.app.name}"
    rolling: "logs/${solon.app.name}_%d{yyyy-MM-dd}/%i.log"
    maxFileSize: "10 MB"
    maxHistory: "7"

solon.logging.logger:
  "root": #默认记录器配置
    level: DEBUG
  "io.netty":
    level: WARN

#folkmq.access:
#  user1 : "YapLHTx19RlsEE16"
#  user2 : "YapLHTx19RlsEE16"