version: '3.5'
services:
  folkmq-broker:
    image: noearorg/folkmq-broker:1.0.24
    container_name: folkmq-broker
    ports:
      - 8602:8602
      - 18602:18602
    volumes:
      - ./data/broker:/data
      - ./logs/broker:/logs
    environment:
      - folkmq.admin=admin  #管理后台密码（暂时没有管理后台）
#      - folkmq.access.ak1=sk1 #消息访问账号，可以配置多个
#      - folkmq.access.ak2=sk2
      - TZ=Asia/Shanghai
    networks:
      folkmq:
        aliases:
          - folkmq-broker
  folkmq-server1:
    image: noearorg/folkmq-server:1.0.24
    container_name: folkmq-server1
    ports:
      - 8611:8602
      - 18611:18602
    volumes:
      - ./logs/server1:/logs
      - ./data/server1:/data
    environment:
      - folkmq.broker=folkmq://folkmq-broker:18602
      - solon.start.ping=folkmq-broker:8602
      - TZ=Asia/Shanghai
    depends_on:
      - folkmq-broker
    networks:
      folkmq:
        aliases:
          - folkmq-server1
  folkmq-server2:
    image: noearorg/folkmq-server:1.0.24
    container_name: folkmq-server2
    ports:
      - 8612:8602
      - 18612:18602
    volumes:
      - ./data/server2:/data
      - ./logs/server2:/logs
    environment:
      - folkmq.broker=folkmq://folkmq-broker:18602
      - solon.start.ping=folkmq-broker:8602
      - TZ=Asia/Shanghai
    depends_on:
      - folkmq-broker
    networks:
      folkmq:
        aliases:
          - folkmq-server2
networks:
  folkmq:
    name: folkmq
    driver: bridge
