version: '3.5'

services:
  folkmq-server:
    image: noearorg/folkmq-server:1.0.22
    container_name: folkmq-server
    environment:
      - folkmq.admin=admin  #管理后台密码
#      - folkmq.access.ak1=sk1 #消息访问账号，可以配置多个
#      - folkmq.access.ak2=sk2
      - TZ=Asia/Shanghai
    ports:
      - 8602:8602           #管理后台端口
      - 18602:18602         #消息服务端口
    volumes:
      - ./logs/server:/logs
      - ./data/server:/data
